steps:
- task: NodeTool@0
  inputs:
    versionSpec: "12.18.3"

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.x'
    addToPath: true

- powershell: |
    $env:npm_config_arch="$(VSCODE_ARCH)"
    $env:npm_config_target="11.2.0"
    $env:npm_config_disturl="https://electronjs.org/headers"
    $env:npm_config_runtime="electron"
    $env:npm_config_build_from_source="true"
    npm install --verbose
  displayName: Install Dependencies

- powershell: |
    npm test
  displayName: Run Tests
  condition: and(succeeded(), eq(variables['VSCODE_ARCH'], 'x64'))